;;; .user-lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from elfeed-nano.el

(autoload 'elfeed-nano--entry-start "elfeed-nano"
"Return the buffer position of the first line of entry N (0-based).

(fn N)")
(autoload 'elfeed-nano-mode "elfeed-nano"
"Lightweight nano-style elfeed UI.

This is a minor mode.  If called interactively, toggle the `Elfeed-Nano
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `elfeed-nano-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "elfeed-nano" '("elfeed-nano-"))


;;; Generated autoloads from mu4e-nano.el

(autoload 'mu4e-nano-mode "mu4e-nano"
"Lightweight nano-style mu4e headers view.

Each message is rendered as a two-line card with a nerd-icons status
glyph, sender, relative date, subject and thread indentation.

Add `mu4e-headers-mode' to `mu4e-nano-mode-hook' (or use
`:hook (mu4e-headers-mode . mu4e-nano-mode)' in use-package) to
enable it in every headers buffer.

This is a minor mode.  If called interactively, toggle the `Mu4e-Nano
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `mu4e-nano-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "mu4e-nano" '("mu4e-nano-"))


;;; Generated autoloads from init-base.el

(register-definition-prefixes "init-base" '("backup-file-name" "childframe-workable-p" "font-available-p" "setup-fonts"))


;;; Generated autoloads from init-completion.el

(register-definition-prefixes "init-completion" '("aiser/completion-preview-inhibit-corfu-p"))


;;; Generated autoloads from init-dashboard.el

(register-definition-prefixes "init-dashboard" '("aiser-use-dashboard" "dashboard-hide-modeline"))


;;; Generated autoloads from init-dev.el

(register-definition-prefixes "init-dev" '("+switch-to-compilation" "aiser/"))


;;; Generated autoloads from init-org.el

(register-definition-prefixes "init-org" '("aiser/vulpea-"))


;;; Generated autoloads from init-utils.el

(register-definition-prefixes "init-utils" '("+copy-current-buffer-name"))


;;; Generated autoloads from init-dired.el

(register-definition-prefixes "init-dired" '("+copy-current-file" "+delete-current-file" "+rename-current-file"))


;;; Generated autoloads from init-emms.el

(register-definition-prefixes "init-emms" '("+emms-"))


;;; Generated autoloads from init-project.el

(register-definition-prefixes "init-project" '("aiser-project-prefix-map"))


;;; Generated autoloads from init-workspaces.el

(register-definition-prefixes "init-workspaces" '("+transient-tab-bar-history" "aiser"))


;;; Generated autoloads from init-workspaces-apps.el

(register-definition-prefixes "init-workspaces-apps" '("aiser/workspace-"))

;;; End of scraped data

(provide '.user-lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .user-lisp-autoloads.el ends here
