;; -*- mode: emacs-lisp; lexical-binding:t; coding: utf-8-emacs; -*-
;; -------------------------------------------------------------------------
;; Tabspaces Session File for Emacs
;; -------------------------------------------------------------------------
;; Created Thu Jan 22 20:09:44 2026

;; Non-project tabs only (project tabs saved separately)

;; Project to tab name mapping:
(setq tabspaces-project-tab-map 'nil)

;; Tabs and buffers:
(setq tabspaces--session-list '((nil "*scratch*" (((min-height . 4) (min-width . 10) (min-height-ignore . 4) (min-width-ignore . 2) (min-height-safe . 1) (min-width-safe . 2) (min-pixel-height . 120) (min-pixel-width . 120) (min-pixel-height-ignore . 120) (min-pixel-width-ignore . 24) (min-pixel-height-safe . 30) (min-pixel-width-safe . 24)) leaf (pixel-width . 1479) (pixel-height . 965) (total-width . 123) (total-height . 32) (normal-height . 1.0) (normal-width . 1.0) (buffer "*scratch*" (selected . t) (hscroll . 0) (fringes 0 0 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated) (point . 148) (start . 1)))) (nil "*scratch*" (((min-height . 4) (min-width . 10) (min-height-ignore . 4) (min-width-ignore . 2) (min-height-safe . 1) (min-width-safe . 2) (min-pixel-height . 120) (min-pixel-width . 120) (min-pixel-height-ignore . 120) (min-pixel-width-ignore . 24) (min-pixel-height-safe . 30) (min-pixel-width-safe . 24)) leaf (pixel-width . 1479) (pixel-height . 965) (total-width . 123) (total-height . 32) (normal-height . 1.0) (normal-width . 1.0) (buffer "*scratch*" (selected . t) (hscroll . 0) (fringes 0 0 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated) (point . 148) (start . 1)))) (("/home/aiser/.emacs.d/lisp/init-ui.el" "/home/aiser/.emacs.d/lisp/init-evil.el" "/home/aiser/.emacs.d/lisp/init-workspaces.el" "/home/aiser/.emacs.d/lisp/init-utils.el") ".emacs.d" (((min-height . 4) (min-width . 10) (min-height-ignore . 4) (min-width-ignore . 2) (min-height-safe . 1) (min-width-safe . 2) (min-pixel-height . 120) (min-pixel-width . 120) (min-pixel-height-ignore . 120) (min-pixel-width-ignore . 24) (min-pixel-height-safe . 30) (min-pixel-width-safe . 24)) leaf (pixel-width . 1479) (pixel-height . 967) (total-width . 123) (total-height . 32) (normal-height . 1.0) (normal-width . 1.0) (parameters (context)) (buffer "init-ui.el" (selected . t) (hscroll . 0) (fringes 0 0 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated) (point . 1747) (start . 1610)) (prev-buffers ("init-utils.el" 369 378) ("init-workspaces.el" 326 861) ("init-evil.el" 4677 4684) ("init-ui.el" 1610 1801))))))