;; -*- mode: emacs-lisp; lexical-binding:t; coding: utf-8-emacs; -*-
;; -------------------------------------------------------------------------
;; Tabspaces Session File for Emacs
;; -------------------------------------------------------------------------
;; Created Thu Jan 22 16:59:47 2026

;; Non-project tabs only (project tabs saved separately)

;; Project to tab name mapping:
(setq tabspaces-project-tab-map 'nil)

;; Tabs and buffers:
(setq tabspaces--session-list '((nil "*tabspaces--placeholder*" (((min-height . 4) (min-width . 10) (min-height-ignore . 4) (min-width-ignore . 2) (min-height-safe . 1) (min-width-safe . 2) (min-pixel-height . 120) (min-pixel-width . 120) (min-pixel-height-ignore . 120) (min-pixel-width-ignore . 24) (min-pixel-height-safe . 30) (min-pixel-width-safe . 24)) leaf (pixel-width . 1479) (pixel-height . 967) (total-width . 123) (total-height . 32) (normal-height . 1.0) (normal-width . 1.0) (buffer " *Old buffer *tabspaces--placeholder**" (selected . t) (hscroll . 0) (fringes 0 0 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated) (point . 1) (start . 1)) (prev-buffers ("init-ui.el" 1 1) ("*scratch*" 1 148)))) (nil "*scratch*" (((min-height . 4) (min-width . 10) (min-height-ignore . 4) (min-width-ignore . 2) (min-height-safe . 1) (min-width-safe . 2) (min-pixel-height . 120) (min-pixel-width . 120) (min-pixel-height-ignore . 120) (min-pixel-width-ignore . 24) (min-pixel-height-safe . 30) (min-pixel-width-safe . 24)) leaf (pixel-width . 1479) (pixel-height . 967) (total-width . 123) (total-height . 32) (normal-height . 1.0) (normal-width . 1.0) (buffer "*scratch*" (selected . t) (hscroll . 0) (fringes 0 0 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated) (point . 148) (start . 1)) (prev-buffers ("*scratch*" 1 148)))) (("/home/aiser/.emacs.d/lisp/init-evil.el" "/home/aiser/.emacs.d/lisp/init-ui.el" "/home/aiser/.emacs.d/lisp/init-workspaces.el" "/home/aiser/.emacs.d/lisp/init-utils.el") ".emacs.d" (((min-height . 4) (min-width . 43) (min-height-ignore . 4) (min-width-ignore . 7) (min-height-safe . 1) (min-width-safe . 4) (min-pixel-height . 120) (min-pixel-width . 516) (min-pixel-height-ignore . 120) (min-pixel-width-ignore . 84) (min-pixel-height-safe . 30) (min-pixel-width-safe . 48)) hc (pixel-width . 1479) (pixel-height . 967) (total-width . 123) (total-height . 32) (normal-height . 1.0) (normal-width . 1.0) (combination-limit) (leaf (pixel-width . 396) (pixel-height . 967) (total-width . 33) (total-height . 32) (normal-height . 1.0) (normal-width . 0.2647058823529412) (parameters (window-side . left) (window-slot . -1) (context)) (buffer " *SIDE :: .emacs :: 01/22/26|16:52:19" (selected) (hscroll . 0) (fringes 3 1 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated . t) (point . 456) (start . 1)) (prev-buffers ("init-evil.el" 1 1))) (leaf (last . t) (pixel-width . 1083) (pixel-height . 967) (total-width . 90) (total-height . 32) (normal-height . 1.0) (normal-width . 0.7352941176470589) (parameters (context)) (buffer "init-evil.el" (selected . t) (hscroll . 0) (fringes 0 0 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated) (point . 5138) (start . 4757)) (prev-buffers ("init-evil.el" 4757 5139) ("init-ui.el" 1610 1801) ("init-workspaces.el" 326 861) ("init-utils.el" 369 378)))))))