# Pyhton lsp
[language-server.ty]
command = "ty"
args = ["server"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "python"
language-id = "python"
file-types = ["py"]
roots = ["pyproject.toml", ".git"]
language-servers = ["ty", "ruff"]

# Go lsp
[language-server.gopls]
command = "gopls"

[language-server.gopls.config]
gofumpt = true

[language-server.gopls.config.hints]
assignVariableTypes = true
parameterNames = true

[[language]]
name = "go"
language-id = "go"
file-types = ["go"]
roots = ["go.mod", "go.work"]
language-servers = ["gopls"]

#Rust lsp
[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

[[language]]
name = "rust"
language-id = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", ".git"]
language-servers = ["rust-analyzer"]

 #Qml lsp
[language-server.qmlls]
command = "qmlls6"

[[language]]
name = "qml"
language-id = "qml"
file-types = ["qml"]
roots = [".git"]
language-servers = ["qmlls"]

#Lua lsp
[language-server.lua-language-server]
command = "lua-language-server"

[language-server.lua-language-server.config.Lua.hint]
enable = true
arrayIndex = "Enable"
setType = true
paramName = "All"
paramType = true
await = true

[[language]]
name = "lua"
file-types = ["lua", "rockspec"]
roots = [".luarc.json", ".luacheckrc", ".stylua.toml", "selene.toml", ".git"]
language-servers = ["lua-language-server"]
